# Generated by Django 4.0.5 on 2022-07-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample', to='lab_management.testrequest'),
        ),
    ]
