# Generated by Django 4.0.5 on 2022-07-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='type',
        ),
        migrations.AddField(
            model_name='testrequest',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_management.sampletype'),
        ),
    ]
