# Generated by Django 4.0.5 on 2022-06-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0005_alter_testrequest_proccessing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_management.sample'),
        ),
    ]
