# Generated by Django 4.0.5 on 2022-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0006_alter_testrequest_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_of_collection',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_of_result',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab_reference',
            field=models.PositiveIntegerField(max_length=150),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='proccessing_status',
            field=models.CharField(choices=[('started', 'STARTED'), ('in_progress', 'IN PROGRESS'), ('completed', 'COMPLETED')], max_length=50),
        ),
    ]
