# Generated by Django 4.0.5 on 2022-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0007_alter_sample_date_of_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='lab_reference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
