# Generated by Django 4.0.5 on 2022-06-23 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.DateTimeField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('surname', models.CharField(max_length=15)),
                ('given_name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=2)),
                ('Nationality', models.CharField(max_length=10)),
                ('patient_id', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
