# Generated by Django 4.0.5 on 2022-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_remove_patient_nationality_remove_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
