# Generated by Django 4.0.5 on 2022-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0005_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='identification',
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
